# Generated by Django 5.0.4 on 2026-05-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('notification_type', models.CharField(choices=[('attendance', 'Attendance'), ('fee_reminder', 'Fee Reminder'), ('fee_receipt', 'Fee Receipt'), ('timetable', 'Timetable'), ('annual_pdf', 'Annual PDF')], max_length=30)),
                ('recipient_mobile', models.CharField(max_length=20)),
                ('message_preview', models.TextField(blank=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='institutes.institute')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
