# Generated by Django 5.0.4 on 2026-05-31 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('target_audience', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='institutes.institute')),
            ],
            options={
                'db_table': 'broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('notification_type', models.CharField(choices=[('attendance', 'Attendance'), ('fee_reminder', 'Fee Reminder'), ('fee_receipt', 'Fee Receipt'), ('timetable', 'Timetable'), ('annual_pdf', 'Annual PDF')], max_length=30)),
                ('recipient_mobile', models.CharField(max_length=20)),
                ('message_preview', models.TextField(blank=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='institutes.institute')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
