# Generated by Django 5.0.4 on 2026-06-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_alter_institute_status'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment_overdue', 'Payment Overdue'), ('payment_due_today', 'Payment Due Today'), ('trial_expiring', 'Trial Expiring'), ('upgrade_request', 'Upgrade Request'), ('downgrade_request', 'Downgrade Request'), ('institute_joined', 'Institute Joined'), ('payment_received', 'Payment Received'), ('info', 'Info')], max_length=40)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warn', 'Warning'), ('info', 'Info'), ('success', 'Success'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('sub', models.CharField(blank=True, max_length=300)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='institutes.institute')),
            ],
            options={
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
