# Generated by Django 5.0.4 on 2026-05-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='monthly_fee_basic',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='monthly_fee_premium',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='monthly_fee_institute',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='monthly_fee_institute_pro',
            field=models.DecimalField(decimal_places=2, default=6000, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='monthly_fee_solo',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='institute',
            name='plan',
            field=models.CharField(choices=[('solo', 'Solo'), ('institute', 'Institute'), ('institute_pro', 'Institute Pro')], default='institute', max_length=20),
        ),
    ]
