# Generated by Django 5.0.4 on 2026-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('trial', 'Trial'), ('active', 'Active'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending', max_length=20),
        ),
    ]
