# Generated by Django 5.0.4 on 2026-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0002_alter_institute_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="institutes/logos/"
            ),
        ),
    ]
