# Generated by Django 5.0.4 on 2026-05-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPromotionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_sources', to='academics.batch')),
                ('target_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='academics.batch')),
            ],
            options={
                'unique_together': {('source_batch', 'academic_year')},
            },
        ),
    ]
