# Generated by Django 5.0.4 on 2026-05-31 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPromotionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=100)),
                ('academic_year', models.PositiveIntegerField()),
                ('is_passout', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_promotions', to='academics.batch')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_promotion_maps', to='institutes.institute')),
            ],
            options={
                'db_table': 'batch_promotion_maps',
                'unique_together': {('institute', 'batch_code', 'academic_year')},
            },
        ),
    ]
