# Generated by Django 5.0.4 on 2026-05-31 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_batch_image_subject_image_teacher_image'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpromotionmap',
            name='target_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='academics.batch'),
        ),
    ]
