# Generated by Django 5.0.4 on 2026-05-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutetransaction',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='institutes.institute'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('institute', 'month')},
        ),
    ]
