# Generated by Django 5.0.4 on 2026-06-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutetransaction',
            name='category',
            field=models.CharField(choices=[('utility_bill', 'Utility Bill'), ('staff_salary', 'Staff Salary'), ('rent', 'Rent'), ('maintenance', 'Maintenance'), ('sponsorship', 'Sponsorship'), ('platform_fee', 'Platform Fee'), ('other_income', 'Other Income'), ('other', 'Other')], max_length=30),
        ),
    ]
