# Generated by Django 5.0.4 on 2026-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_institutetransaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
