# Generated by Django 5.0.4 on 2026-06-09 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_payment_slip_partial'),
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Invoice Created'), ('payment_recorded', 'Payment Recorded'), ('marked_paid', 'Marked Paid'), ('reverted_pending', 'Reverted to Pending'), ('status_changed', 'Status Changed'), ('amount_changed', 'Amount Changed'), ('slip_uploaded', 'Slip Uploaded'), ('advance_applied', 'Advance Applied')], max_length=30)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('actor', models.CharField(blank=True, default='Admin', max_length=120)),
                ('amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_activities', to='institutes.institute')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='billing.invoice')),
            ],
            options={
                'db_table': 'invoice_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
