# Generated by Django 5.0.4 on 2026-06-09 18:07

import apps.billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoiceactivity'),
        ('institutes', '0002_alter_institute_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slip', models.FileField(blank=True, null=True, upload_to=apps.billing.models.invoice_payment_slip_upload_to)),
                ('reference_note', models.CharField(blank=True, default='', max_length=200)),
                ('actor', models.CharField(blank=True, default='Admin', max_length=120)),
                ('is_advance', models.BooleanField(default=False)),
                ('source_month', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='institutes.institute')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
            options={
                'db_table': 'invoice_payments',
                'ordering': ['created_at'],
            },
        ),
    ]
