# Generated by Django 5.0.4 on 2026-06-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Invoice Created'), ('payment_recorded', 'Payment Recorded'), ('marked_paid', 'Marked Paid'), ('reverted_pending', 'Reverted to Pending'), ('status_changed', 'Status Changed'), ('amount_changed', 'Amount Changed'), ('slip_uploaded', 'Slip Uploaded'), ('advance_applied', 'Advance Applied'), ('payment_edited', 'Payment Edited'), ('payment_removed', 'Payment Removed')], max_length=30),
        ),
    ]
