# Generated by Django 5.0.4 on 2026-08-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_qr_token_unique"),
        ("billing", "0008_alter_invoiceactivity_action"),
        ("fees", "0002_feepayment_method_feepayment_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutetransaction",
            name="source_fee_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institute_transaction",
                to="fees.feepayment",
            ),
        ),
        migrations.AddField(
            model_name="institutetransaction",
            name="source_teacher_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institute_transaction",
                to="academics.teacherpayment",
            ),
        ),
        migrations.AlterField(
            model_name="institutetransaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("student_fee", "Student Fees"),
                    ("utility_bill", "Utility Bill"),
                    ("staff_salary", "Staff Salary"),
                    ("rent", "Rent"),
                    ("maintenance", "Maintenance"),
                    ("sponsorship", "Sponsorship"),
                    ("platform_fee", "Platform Fee"),
                    ("other_income", "Other Income"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
