# Generated by Django 5.0.4 on 2026-08-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_institutetransaction_source_fee_payment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institutetransaction",
            name="source_fee_payment",
        ),
        migrations.RemoveField(
            model_name="institutetransaction",
            name="source_teacher_payment",
        ),
        migrations.AddField(
            model_name="institutetransaction",
            name="is_auto_synced",
            field=models.BooleanField(default=False),
        ),
    ]
