# Generated by Django 5.0.4 on 2026-05-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='batchteacherconfig',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_config', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='exam',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='exammark',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.exam'),
        ),
        migrations.AddField(
            model_name='exammark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student'),
        ),
        migrations.AddField(
            model_name='examscheduleitem',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='academics.exam'),
        ),
        migrations.AddField(
            model_name='subject',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='batch',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='batch',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='teacheradvance',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_advances', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='teacheradvance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='academics.teacher'),
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payments', to='institutes.institute'),
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='exammark',
            unique_together={('exam', 'student', 'subject')},
        ),
    ]
