# Generated by Django 5.0.4 on 2026-05-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_batch_subject_remove_batch_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='grade',
            new_name='batch',
        ),
    ]
