# Generated by Django 5.0.4 on 2026-05-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_grade_subject_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='batches/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
    ]
