# Generated by Django 5.0.4 on 2026-06-14 16:39

import apps.academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_batch_backfill_grade_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qr_token',
            field=models.CharField(blank=True, db_index=True, default=apps.academics.models._gen_teacher_token, max_length=32),
        ),
    ]
