# Generated by Django 5.0.4 on 2026-06-14 16:40

import apps.academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_backfill_qr_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='qr_token',
            field=models.CharField(db_index=True, default=apps.academics.models._gen_teacher_token, max_length=32, unique=True),
        ),
    ]
