# Generated by Django 5.0.4 on 2026-06-14 16:39

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_token',
            field=models.CharField(blank=True, db_index=True, default=apps.students.models._gen_token, max_length=32),
        ),
    ]
