# Generated by Django 5.0.4 on 2026-05-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='batch',
        ),
    ]
