# Generated by Django 5.0.4 on 2026-05-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_grade_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
