# Generated by Django 5.0.4 on 2026-06-14 16:40

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_backfill_qr_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_token',
            field=models.CharField(db_index=True, default=apps.students.models._gen_token, max_length=32, unique=True),
        ),
    ]
