# Generated by Django 5.0.4 on 2026-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_qr_token_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
    ]
