# Generated by Django 5.0.4 on 2026-08-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feepayment",
            name="method",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="reference_no",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
